export const APP_STATE = 'APP_STATE';
export const LIST_STATE = 'LIST_STATE';

//获取正在热映的电影
export const APP_GETMOVINGLIST = 'APP_GETMOVINGLIST';

//获取电影条目信息
export const LIST_GETMOVING_INFO = 'LIST_GETMOVING_INFO';

//点击显示更多状态
export const LIST_SETSHOWMOREBUTTON_STATE = 'LIST_SETSHOWMOREBUTTON_STATE';

//存储地理位置信息
export const APP_GETCURRENTPOSITION = 'APP_GETCURRENTPOSITION';

//存储演员列表
export const LIST_SETACTORITEM = 'LIST_SETACTORITEM';

//储存选中的演员信息
export const LIST_CHECKACTORINFO = 'LIST_CHECKACTORINFO';

//存储用户是否看过按钮状态
export const LIST_HASREADMOVE = 'LIST_HASREADMOVE';

//评分状态
export const LIST_SCORECOUNTER = 'LIST_SCORECOUNTER' //

//获取电影剧照
export const LIST_MOVEPHOTOS = 'LIST_MOVEPHOTOS';

//存储用户坐标信息
export const CINEMA_CURRENTPOSITION = 'CINEMA_CURRENTPOSITION';

//存储影院信息
export const CINEMA_GETCINEMALIST = 'CINEMA_GETCINEMALIST';