export const APP_STATE = 'APP_STATE';
export const LIST_STATE = 'LIST_STATE';

//获取正在热映的电影
export const APP_GETMOVINGLIST = 'APP_GETMOVINGLIST';

//获取电影条目信息
export const LIST_GETMOVING_INFO = 'LIST_GETMOVING_INFO';

//点击显示更多状态
export const LIST_SETSHOWMOREBUTTON_STATE = 'LIST_SETSHOWMOREBUTTON_STATE';